### ISSUE TITLE
컴포넌트 디자인 수정 및 데이터 요청 기능 추가

### ISSUE THREAD

**Issue by inhooinu** [pda5th-TheOne/front#20]
## Description

- `Main.jsx`, `TIL.jsx`, `Practice.jsx`, `Question.jsx`의 디자인 문제 수정
- `TIL.jsx`와 `Practice.jsx`에 axios를 이용한 데이터 요청 추가

## Todo

- [x] `Main.jsx`, `TIL.jsx`, `Practice.jsx`, `Question.jsx`의 레이아웃 스타일 수정
- [x] `TIL.jsx`에 axios 데이터 요청 구현
- [x] `Practice.jsx`에 axios 데이터 요청 구현
