### ISSUE TITLE
로그인 및 회원가입 페이지 디자인 수정 및 회원가입 성공 시 리디렉션 구현

### ISSUE THREAD

**Issue by JangWooJin1** [pda5th-TheOne/front#26]
## Description

로그인 및 회원가입 페이지의 디자인을 수정하고, 회원가입 성공 시 로그인 페이지로 리디렉션되도록 기능을 추가

## Todo

- [x] 로그인 및 회원가입 페이지 디자인 수정
- [x] 회원가입 성공 시 로그인 페이지로 리디렉션 구현
- [x] 로그인 페이지에 회원가입 성공 메시지 표시
