### ISSUE TITLE
프론트엔드 타이머 기능 및 상세페이지 링크 구현

### ISSUE THREAD

**Issue by JangWooJin1** [pda5th-TheOne/front#33]
## Description

프론트엔드에서 타이머 UI를 구현하고, 각 실습 상세페이지(`/practice/1`)로 이동할 수 있는 기능을 추가

## Todo

- [x] 각 실습 상세페이지(`/practice/1`)로 이동하는 링크 추가
- [x] 타이머 컴포넌트 분리
- [x] 타이머 시작, 일시정지, 재개, 리셋 버튼 구현
- [x] SSE를 통해 타이머 상태를 실시간으로 업데이트하는 기능 구현
