### ISSUE TITLE
React 프로젝트 Docker 컨테이너화 및 CI/CD 파이프라인 구축

### ISSUE THREAD

**Issue by JangWooJin1** [pda5th-TheOne/front#4]
## Description

- React 프로젝트를 Docker로 컨테이너화하여 Nginx를 통해 배포할 수 있도록 설정
  - Dockerfile을 작성하여 Node.js로 빌드하고 Nginx로 정적 파일을 서빙하도록 구성
  - Nginx 설정 파일을 작성하여 SPA 라우팅을 지원
- GitHub Actions를 통해 main 브랜치에 push될 때 Docker Hub에 이미지를 푸시하고, EC2 서버에 자동 배포하는 CI/CD 파이프라인 구성

## Todo

- [x] Docker 환경 설정
  - [x] Dockerfile 작성: React 앱을 빌드하고 Nginx로 서빙할 수 있도록 설정
  - [x] Nginx 설정 파일 작성: SPA 라우팅 지원 및 정적 파일 제공 설정

- [x] GitHub Secrets 설정 ( `DOCKER_USERNAME`, `DOCKER_PASSWORD`, `EC2_HOST`, `EC2_USER`, `EC2_KEY` 추가 )

- [x] GitHub Actions 워크플로우 구성
  - [x] `.github/workflows/deploy.yml` 파일 작성
  - [x] GitHub Actions에서 Docker Hub 로그인 및 이미지 빌드 후 푸시 설정
  - [x] GitHub Actions가 EC2 서버에 SSH 접속해 최신 Docker 이미지를 pull하고 컨테이너 실행하도록 설정
