### ISSUE TITLE
상세 페이지 작업

### ISSUE THREAD

**Issue by JangWooJin1** [pda5th-TheOne/front#5]
## Description

- 날짜별 상세 페이지 생성

## Todo

- [x] pages/detail/Main.jsx
- [x] pages/detail/TIL.jsx
- [x] pages/detail/Practice.jsx
- [x] pages/detail/Question.jsx
