### ISSUE TITLE
404 Not Found 페이지 스타일 개선

### ISSUE THREAD

**Issue by JangWooJin1** [pda5th-TheOne/front#51]
## Description

- 404 Not Found 페이지를 간단히 꾸며 사용자 경험을 개선

## Todo

- [x] 404 페이지에 일러스트 추가
- [x] 사용자 친화적인 메시지 적용
- [x] 메인 페이지로 이동하는 버튼 구현
