### ISSUE TITLE
실습 페이지 구현

### ISSUE THREAD

**Issue by JangWooJin1** [pda5th-TheOne/front#8]
## Description

실습 페이지의 UI 뼈대 코드를 작성하여 더미 데이터를 활용한 기본 레이아웃을 구현하는 작업
이 작업은 실제 백엔드 API 요청 없이 화면 구성과 컴포넌트 배치를 확인할 수 있도록 더미 데이터를 사용

## Todo

- [x] Answer, Assignment, Submit 컴포넌트 추가 및 기본 UI 레이아웃 구현
- [x] Logo, UserName 등의 공통 컴포넌트 추가
- [x] Practice 페이지에 라우터 설정 및 네비게이션 적용
- [x] 전역 스타일링을 위해 `App.jsx`에 Bootstrap 라이브러리 임포트
